# Generated by Django 3.2.19 on 2023-06-13 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceProject',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(max_length=100)),
                ('end_date', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=100)),
                ('is_recipient', models.CharField(max_length=100)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaries.household')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cash_offer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assistance_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaries.assistanceproject')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaries.household')),
            ],
        ),
    ]
